# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: justparty
      POSTGRES_USER: justparty
      POSTGRES_DB: justparty

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
